In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 問題1 行列を手計算する

AとBの行列の積を<br>C=[[c11,c12,c13],<br>
                         [c21,c22,c23],<br>
                         [c31,c32,c33]]とする
                         
この時、手計算すると、<br>
c11 = (-1)*0 + 2*0 + 3*2=6 <br>
c12 = (-1)*2 + 2*2 + 3*9=29<br>
c13 = (-1)*1 + 2*(-8) + 3*(-1)=-20<br>
c21 = 4*0 + (-5)*0 + 6*2=12<br>
c22 = 4*2 + (-5)*2 + 6*9=52<br>
c23 = 4*1 + (-5)*(-8) + 6*(-1)=38<br>
c31 = 7*0 + 8*0 + (-9)*2=-18<br>
c32 = 7*2 + 8*2 + (-9)*9=-51<br>
c33 = 7*1 + 8*(-8) + (-9)*(-1)=-48<br>

以上より、行列A,Bの積Cは、<br>
C=[[6,29,-20],<br>
[12,52,38],<br>
[-18,-51,-48]]となる


               

# 問題2 NumPyの関数による計算

In [2]:
np.dot(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 問題3 ある要素の計算を実装

In [5]:
C = np.zeros((3,3))
#0行目0列を計算する
mat_par_sum = 0
for i in range(C.shape[0]):
    mat_par_sum += a_ndarray[0,i] * b_ndarray[i,0]
print('0行目0列の値は{}'.format(mat_par_sum))

0行目0列の値は6


# 問題4 行列積を行う関数の作成

In [10]:
def calc_matrix(a,b):
    C = np.zeros((a.shape[0],b.shape[1]))
    for i in range(C.shape[0]):
        for j in range(C.shape[1]):
            for k in range(a.shape[1]):
                 C[i,j] += a[i,k]*b[k,j]
    return C
    
                    

In [13]:
#2 x 3の行列の積の計算なども可能
calc_matrix(a_ndarray[1:,:],b_ndarray)

array([[ 12.,  52.,  38.],
       [-18., -51., -48.]])

# 問題5 計算が定義されない入力を判定する

In [17]:
def calc_matrix_and_check(a,b):
    C = np.zeros((a.shape[0],b.shape[1]))
    if a.shape[1] == b.shape[0]:
        for i in range(C.shape[0]):
            for j in range(C.shape[1]):
                for k in range(a.shape[1]):
                    C[i,j] += a[i,k]*b[k,j]
        return C
    else:
        print('{}の形式の行列と{}の形式の積は計算出来ません。'.format(a.shape,b.shape))
        
        return None

In [18]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
calc_matrix_and_check(d_ndarray_,e_ndarray)

(2, 3)の形式の行列と(2, 3)の形式の積は計算出来ません。


# 問題６ 転置

In [21]:
print(np.dot(d_ndarray_.T,e_ndarray))

[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
